#71 vlsr
necst-telescope/nercst pull request #76
Opened 2024-07-17 10:56 UTC by FumikaDemachi

**Checks**

- [x] Debugging completed
- [ ] Please debug me

**Related Issue**

This PR closes #71 .

2024-07-22 17:20 UTC, FumikaDemachi commented
This feature needs the latest neclib (#566).

2024-07-23 03:55 UTC, r-yamada1998 requested changes
I requested changes on the draft

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/coords_converter.py
> +        lon_list.append(lon)
numpy arrayに変換しておきましょう

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/coords_converter.py
> +        lon_list, lat_list, frame="altaz", obstime=obstime, location=config.location
lon_list -> lon_arr

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/obsvelocity_utils.py
> +    obs = Observer(location)
obs -> observer

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/obsvelocity_utils.py
> +    channel_array,
channel_array -> channel_integer_numbers

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/obsvelocity_utils.py
> +    observed_GHz_array = channel_array * freq_resolution
obsfreq_array

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/obsvelocity_utils.py
> +        channel_array,
channel_array

2024-07-23 03:55 UTC, r-yamada1998 commented on nercst/core/obsvelocity_utils.py
> +        data_array,
data_array -> spec_array

2024-07-23 12:10 UTC, r-yamada1998 requested changes
中身は今のでokだとお思います。
話が二転三転しちゃってるけど、coords_converterとobs_velocity_utilsをまとめて、
```
multidimensional_coordinates
```
にまとめましょう。これで完成です。

2024-07-23 13:05 UTC, merged